version: '3.8'
services:

  bookmarker-api:
    build:
      context: bookmarker-api
      dockerfile: "Dockerfile.layered"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_POSTGRES_USER: root
      SPRING_POSTGRES_PASSWORD: root
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - bookmarker-db
